### ISSUE TITLE
Salesforce component token is automatically expiring 

### ISSUE THREAD

**Issue by ankitmagicsoft** [elasticio/salesforce-component#46] opened 2019-02-07 10:49 UTC
Salesforce component token is automatically expiring and not refreshing the token automatically if the flow is scheduled to run in a couple of hours or if XPC system down for a couple of hours.

**Comment by zubairov** [comment] 2019-02-07 12:10
@ankitmagicsoft could you please describe the following:

- [ ] steps to reproduce

- [ ] expected result

- [ ] actual result

we will try to reproduce the issue and fix

**Comment by ankitmagicsoft** [comment] 2019-02-08 08:50
**steps to reproduce: **: scheduled the salesforce component to run in a couple of hours or stop the flow and run after a couple of hours then authenticated token will not refresh automatically and throw the refresh token expire error.
   **expected result: ** salesforce Token should not expire.
   **Actual result: **  Getting refresh token has been expired.

**Comment by zubairov** [comment] 2019-03-01 10:08
@khanzadyan can we reproduce it?

**Comment by khanzadyan** [comment] 2019-03-04 14:41
@zubairov Initial tests show the token gets expired after around 72 hours after the initial verification. The number differs from system to system. Still investigating to pinpoint the exact conditions.

**Comment by juhrmacher** [comment] 2019-03-05 07:46
@tigran. This only happens on XPC, right?

**Comment by ShkarupaNick** [comment] 2019-03-14 13:15
The Issue in the count of refresh token per one user. It should be less then 5 (1-4). If you create new credential and ask new refresh token, the oldest from them will be revoked and you will get error `refresh token has been expired`
Suggestions:
1) Use one credentials for all flows per workspace
2) You can create 4 or less credentials for one user login (so, according to suggestion 1, you can use one user login for 1-4 workspaces)

@ankitmagicsoft, please make sure, that you don't use more than 4 credentials with the same user login?

**Comment by zubairov** [comment] 2019-03-14 13:19
@ShkarupaNick could you please elaborate about limitations of 'refresh token per one user'?

do you have a link to the Salesforce documentation describing it?

**Comment by ShkarupaNick** [comment] 2019-03-15 09:58
@zubairov, This information was received in investigation and testing way. 
But you can find some information in the [salesforce documentation](https://help.salesforce.com/articleView?id=remoteaccess_request_manage.htm&type=5)

**Comment by ankitmagicsoft** [comment] 2019-03-15 12:39
@ShkarupaNick I'm using only one credential for all the flow

**Comment by zubairov** [comment] 2019-03-15 13:32
It's an interesting situation - according to the Salesforce [documentation](https://help.salesforce.com/articleView?id=remoteaccess_request_manage.htm&type=5):

> Each connected app allows five unique approvals per user. When a sixth approval is made, the oldest approval is revoked

The behaviour and error described in this bug are caused by the fact that **same user** account was authenticated with **same OAuth Application** (OAuth Client) more than 4 times. This is not the bug in the connector but a feature of the Salesforce platform that automatically invalidates the oldest `refresh_token` as soon as a number of given refresh tokens for an individual user account exceeds 4.

I will close this issue as it's not a behavior we could influence by connector's code.

**Closed by zubairov** 2019-03-15 13:32 UTC
